# Generated by Django 4.1.7 on 2023-02-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_alter_trait_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
