# Generated by Django 4.1.6 on 2023-02-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_alter_group_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
