# Generated by Django 4.1.6 on 2023-02-21 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_sex"),
        ("groups", "0008_alter_group_pets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="pets",
        ),
        migrations.AddField(
            model_name="group",
            name="pet",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="group",
                to="pets.pet",
            ),
            preserve_default=False,
        ),
    ]
