# Generated by Django 4.1.6 on 2023-02-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0009_remove_group_pets_group_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
