# Generated by Django 4.1.6 on 2023-02-21 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0010_alter_group_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="pet",
            new_name="pets",
        ),
    ]
