# Generated by Django 4.1.6 on 2023-02-21 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0011_rename_pet_group_pets"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="pets",
            new_name="pet",
        ),
    ]
