# Generated by Django 4.1.7 on 2023-02-22 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0016_remove_group_pet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="scientific_name",
            new_name="name",
        ),
    ]
