# Generated by Django 4.1.7 on 2023-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0018_rename_name_group_scientific_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
